In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\DeLL\Downloads\customer_shopping_behavior.csv")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [12]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [13]:
df.columns = df.columns.str.lower()

In [14]:
df.columns = df.columns.str.replace(' ' , '_')

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [20]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [25]:
labels=['Young Adult', 'Adult' , 'Middle Age', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [26]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55   Middle Age
1   19  Young Adult
2   50   Middle Age
3   21  Young Adult
4   45   Middle Age
5   46   Middle Age
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57   Middle Age

In [30]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 months' : 90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [31]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [35]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [36]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [37]:
df.drop('promo_code_used', axis=1)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Age,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Age,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Age,365.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7.0
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle Age,14.0
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle Age,90.0
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7.0
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle Age,90.0

In [38]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchase_frequency_days'],
      dtype='str')

In [39]:
%pip install mysql-connector-python pandas sqlalchemy

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: pandas in C:\Users\DeLL\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.6)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.54-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\DeLL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\DeLL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\DeLL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.4)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.6-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\DeLL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\DeLL\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading mysql_connector_python-26.7.0-cp314-cp314-win_amd64.whl (18.2 MB)
   ---------------------------------------- 0.0/18.2 MB ? eta -:--:--
   ------ --------------------------------- 2.9/18.2 MB 14.4 MB/s eta 0:00:02
   ---------- ----------------------------- 4.7/18.2 MB 12.1 MB/s eta 0:00:02
   ------------ --------------------------- 5.5/18.2 MB 10.1 MB/s eta 0:00:02
   ------------ --------------------------- 5.8/18.2 MB 8.6 MB/s eta 0:00:02
   ------------- -------------------------- 6.3/18.2 MB 6.5 MB/s eta 0:00:02
   --------------- ------------------------ 7.1/18.2 MB 5.7 MB/s eta 0:00:02
   ----------------- ---------------------- 8.1/18.2 MB 5.4 MB/s eta 0:00:02
   -------------------- ------------------- 9.2/18.2 MB 5.4 MB/s eta 0:00:02
   ----------------------- ---------------- 10.5/18.2 MB 5.5 MB/s eta 0:00:02
   ------------------------- -------------- 11.8/18.2 MB 5.7 MB/s eta 0:00:02
   --------------------------- ------------ 12.3/18.2 MB 5.4 MB/s eta 0:00:02
   ---------------------------- ----------- 13.1/18.2 MB 5.2 MB/s eta 0:00:01
   ------------------------------- -------- 14.2/18.2 MB 5.2 MB/s eta 0:00:01
   --------------------------------- ------ 15.5/18.2 MB 5.2 MB/s eta 0:00:01
   ------------------------------------ --- 16.8/18.2 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  17.8/18.2 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 18.2/18.2 MB 5.2 MB/s  0:00:03
Downloading sqlalchemy-2.0.54-cp314-cp314-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.2 MB 4.6 MB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.2 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 4.9 MB/s  0:00:00
Downloading greenlet-3.5.6-cp314-cp314-win_amd64.whl (327 kB)
Installing collected packages: mysql-connector-python, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ---------------------------------------- 0/3 [mysql-connector-python]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.6 mysql-connector-python-26.7.0 sqlalchemy-2.0.54
Note: you may need to restart the kernel to use updated packages.

In [41]:
import mysql.connector
import pandas as pd

In [44]:
import mysql.connector
import pandas as pd
connection = mysql.connector.connect(
    host = "localhost",
    port=3306,
    user="root",
    password = "root"
)
if connection.is_connected():
    print("Successfully connected to mysql")

Successfully connected to mysql

In [46]:
print(connection.is_connected())

True

In [47]:
cursor = connection.cursor()
cursor.execute("SHOW DATABASES")
for database in cursor:
    print(database[0])

absc
bootcamp
ecommerce
employee
hdb
hospitaldb
information_schema
mydatabase
mysql
performance_schema
pizza_hut
retail
sakila
sanket
stud_info
stude_info
student
student1
student_manegment
studentbd
sys
world
xcvd
xcvd1

In [48]:
cursor = connection.cursor()
cursor.execute("CREATE DATABASE IF NOT EXISTS customer_db")
print("Database Created Successfully")

Database Created Successfully

In [51]:
cursor.execute("USE customer_db")
print("Database selected successfully")

Database selected successfully

In [52]:
from sqlalchemy import create_engine

In [53]:
engine = create_engine(
    "mysql+mysqlconnector://root:root@localhost:3306/customer_db")

In [55]:
df.to_sql(
    name="customer_shopping_behavior",
    con=engine,
    if_exists="replace",
    index=False
)
print("Data succefully imported")

Data succefully imported